### PR TITLE
Add option to disable credits after Disqus widget.

### PR DESCRIPTION
**Pull request by MadAnd**

### CODE REVIEW

**Comment by kartik-v** [comment]
Not required... just set `credits` property to empty string - it will be the same as this PR.

**Comment by kartik-v** [comment]
Not required... just directly set `credits` property to empty string in your widget (which is what you are doing in this PR as well).

**Comment by MadAnd** [comment]
If I would set ```credits``` property to ```''```, then according to line 61
```
$this->noscript = Yii::t('kvsocial', 'Please enable JavaScript to view the {pluginLink}.', ['pluginLink' => $this->credits]);
```
I will get corrupted ```noscript``` block. My patch solves this particular issue. Please, re-consider it.

**Comment by kartik-v** [comment]
Ok done.

**Comment by MadAnd** [comment]
Thanks.

**Pull request merged**
